---
version: 2

workflows:
  version: 2
  build_linux:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: ubuntu:bionic

    steps:
      - run: pwd; ls -al; id -a
      - run: apt update &&
          apt install -y zip grep sudo rubygems git ssh ruby-dev gcc make
      - checkout
      # - run: sudo $(which gem) install github_changelog_generator
      - run: sudo $(which gem) install specific_install
      # - run: sudo $(which gem) specific_install https://github.com/github-changelog-generator/github-changelog-generator
      - run: git clone https://github.com/ameir/github-changelog-generator.git -b v1.15.2-fixes;
         cd github-changelog-generator/ ;
         sudo $(which gem) build github_changelog_generator.gemspec ;
         sudo $(which gem) install -N github_changelog_generator-1.15.2.gem

      - run: sudo $(which ruby) $(which github_changelog_generator) --help ; exit 0
      - run: sudo $(which ruby) $(which github_changelog_generator)
         -u "$CIRCLE_PROJECT_USERNAME"
         -p "$CIRCLE_PROJECT_REPONAME"
         --exclude-tags "echo $(git tag -l '1.[0123].*'| tr '\n' ',')","$(git tag -l '0.*'| tr '\n' ',')"
         --token "$CHANGELOG_GEN_TOKEN"
      - run: sudo chmod a+r /root/project/CHANGELOG.md
      - run: ls -rattlh

      - store_artifacts:
          path: /root/project/CHANGELOG.md
destination: changelog
