name: Generate Changelog

on:
  release:
    types: [published, edited]
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

defaults:
  run:
    shell: bash

jobs:
  gen-changelog:
    runs-on: ubuntu-latest
    environment: genlog_gen_token
    steps:
    - uses: actions/checkout@v2

    - name: install pkgs
      run:  |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt update && sudo apt install -y zip grep sudo ruby rubygems git ssh ruby-dev gcc make
            sudo $(which gem) install specific_install

    - name: install github-changelog-generator
      run:  |
            git clone https://github.com/ameir/github-changelog-generator.git -b v1.15.2-fixes
            cd github-changelog-generator/
            sudo $(which gem) build github_changelog_generator.gemspec
            sudo $(which gem) install -N github_changelog_generator-1.15.2.gem

    - name: run github-changelog-generator
      env:
            CHANGELOG_GEN_TOKEN: ${{ secrets.CHANGELOG_GEN_TOKEN }}
      run:  |
            pwd
            ls -al
            git tag -l '1.[0123].*'| tr '\n' ','
            tags1=$(git tag -l '1.[0123].*'| tr '\n' ',')
            git tag -l '0.*'| tr '\n' ','
            tags2=$(git tag -l '0.*'| tr '\n' ',')
            git tag -l
            echo $tags1
            echo $tags2
            $(which ruby) $(which github_changelog_generator) -u Zoxcore -p Antidote \
               --exclude-tags $tags1,$tags2 \
               --token "$CHANGELOG_GEN_TOKEN"

    - name: chmod
      run:  |
            sudo chmod a+r /home/runner/work/Antidote/Antidote/CHANGELOG.md
            ls -rattlh

    - name: upload IPA file
      uses: actions/upload-artifact@v2
      with:
        name: Changelog
        path: |
          /home/runner/work/Antidote/Antidote/CHANGELOG.md


