name: Nightly

on:
#  push:
#    paths-ignore:
#     - 'README.md'
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

defaults:
  run:
    shell: bash

jobs:
  macos-test-run:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2

    - name: Display the OS Version1
      run: sw_vers -productVersion

    - name: Display the OS Version2
      run: system_profiler SPSoftwareDataType

    - name: xcode compile
      run:  |
            ls -al
            pwd
            id -a
            pod install


