name: Nightly

on:
#  push:
#    paths-ignore:
#     - 'README.md'
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

defaults:
  run:
    shell: bash

jobs:
  macos-test-run:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2

    - name: Display the OS Version1
      run: sw_vers -productVersion

    - name: Display the OS Version2
      run: system_profiler SPSoftwareDataType

    - name: xcode info
      run:  |
            ls -al
            pwd
            id -a
            pod install
            xcode-select --print-path
            xcodebuild -list -workspace Antidote.xcworkspace
            xcodebuild -list -project Antidote.xcodeproj

    - name: xcode compile
      run:  |
            env NSUnbufferedIO=YES xcodebuild -workspace ./Antidote.xcworkspace -scheme Antidote -destination 'platform=iOS Simulator,id=C57FF42C-5786-4BD4-B4AE-0CAC22AA74AD'



