name: Nightly

on:
#  push:
#    paths-ignore:
#     - 'README.md'
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

defaults:
  run:
    shell: bash

jobs:
  macos-compile:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2

    - name: Display the OS Version1
      run: sw_vers -productVersion

    - name: Display the OS Version2
      run: system_profiler SPSoftwareDataType

    - name: xcode info
      run:  |
            ls -al
            pwd
            id -a
            pod install
            xcode-select --print-path
            xcodebuild -list -workspace Antidote.xcworkspace
            xcodebuild -list -project Antidote.xcodeproj

    - name: xcode compile
      run:  |
            echo "iPhone 11 Simulator"
            env NSUnbufferedIO=YES xcodebuild -workspace ./Antidote.xcworkspace -scheme Antidote -destination 'platform=iOS Simulator,id=EAB9614F-3485-4A6D-8EFB-FC2B5EFB0243'

    - name: check compile output
      run:  |
            ls -al /Users/runner/Library/Developer/Xcode/DerivedData/Antidote-bhjjxfvewsypipfpuadvlmuxuzew/Build/Products/Debug-iphonesimulator/Antidote.app/
            file /Users/runner/Library/Developer/Xcode/DerivedData/Antidote-bhjjxfvewsypipfpuadvlmuxuzew/Build/Products/Debug-iphonesimulator/Antidote.app/Antidote

